### PR TITLE
Fix android aarch64 build with libc 0.2.42

### LINKED ISSUE #851: Compilation failure on android with latest libc
Hi,

mio 0.6.16 and libc 0.2.42 doesn't work together on android. 
```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/sys/unix/uds.rs:144:33
    |
144 |                                 len_i32))?;
    |                                 ^^^^^^^ expected u32, found i32

error: aborting due to previous error
```

It seems like it relates to  [this commit in libc](https://github.com/rust-lang/libc/commit/0280db396de7ef8db0ccaf481c0ef93ec304428f#diff-75c7e64ae55ff3f82ee445b1f7a34789)

### PR DESCRIPTION
**Pull request by glebpom**
Fixes #851

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. #850 addressed the same issue and has been merged, so I will close this.
